core/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('change_password/', views.change_password, name='change_password'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'), name='password_reset_complete'),

    path('plans/', views.plans, name='plans'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('user_manual/', views.user_manual, name='user_manual'),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('project/', include('project.urls')),
    path('userprofile/', include('userprofile.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    path('<int:user_id>/', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

userprofile/models.py
from django.db import models
from django_countries.fields import CountryField
from core.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    name = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    about = models.TextField(max_length=225, blank=True, null=True)
    country = CountryField(blank=True, null=True)
    image = models.ImageField(default='profile_pictures/default-user.png', upload_to='profile_pictures')

    def __str__(self):
        return f"{self.user.username}"

userprofile/forms.py
from django import forms
from .models import UserProfile
from django.conf import settings
from django_countries.widgets import CountrySelectWidget
from django.core.exceptions import ValidationError

class CreateUserProfileForm(forms.ModelForm):

    date_of_birth = forms.DateField(required=False, label="Date of birth:" , widget=forms.DateInput(attrs={
            "type": "date",
            "placeholder": "Select a date",
            "class": "form-control"
        }),
    )

    def clean_image(self):
        image = self.cleaned_data.get('image')

        if "default-user.png" not in image:
            if image.size > settings.MAX_UPLOAD_SIZE * 1024 * 1024:
                raise ValidationError(f"Image file exceeds {settings.MAX_UPLOAD_SIZE} mb size limit!")
        return image
    
    class Meta:
        model = UserProfile
        fields = ["name", "date_of_birth", "about", "country", "image"]
        labels = {
            "name": "Name:",
            "about": "About:",
            "country": "Country:",
            "image": "Image:"
        }

        widgets = {
            "name": forms.TextInput(attrs={
                "placeholder": "Your name",
                "class": "form-control"
                }),
            "about": forms.Textarea(attrs={
                "placeholder": "Tell about yourself",
                "class": "form-control",
                "id": "about-input",
                "rows": "3"
            }),
            "country": CountrySelectWidget(attrs={
                "class": "form-control"
            }),
        }

userprofile/views.py
from django.shortcuts import render
from core.models import User
from .models import UserProfile
from django.contrib.auth.decorators import login_required
from .forms import CreateUserProfileForm

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings


# Create your views here.
@login_required(login_url="core:login")
def user_profile(request, user_id):
    user_data = UserProfile.objects.get(pk=user_id)
    user = User.objects.get(pk=user_id)
    return render(request, "userprofile/user_profile.html", {
        "user": user,
        "user_data": user_data
    })

@login_required(login_url="core:login")
def edit_profile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile(user=request.user)

    if request.method == "POST":
        #cancel the edit request
        if request.POST.get("cancel") == "clicked":
            return HttpResponseRedirect(reverse("userprofile:user_profile", args=[request.user.id]))
        
        #Edit the profile
        form = CreateUserProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            #update all profile's data with form's data
            user_profile.name = form.cleaned_data.get("name")
            user_profile.date_of_birth = form.cleaned_data.get("date_of_birth")
            user_profile.about = form.cleaned_data.get("about")
            user_profile.country = form.cleaned_data.get("country")

            #update image only if the file was uploaded
            if len(request.FILES) == 1:
                user_profile.image = request.FILES['image']
            
            user_profile.save()

            return HttpResponseRedirect(reverse("userprofile:user_profile", args=[request.user.id]))
        else:
            return render(request, "userprofile/edit_profile.html", {
                "form": form,
                "max_file_size": settings.MAX_UPLOAD_SIZE
            })
    
    return render(request, "userprofile/edit_profile.html", {
        "form": CreateUserProfileForm(instance=request.user.profile),
        "max_file_size": settings.MAX_UPLOAD_SIZE
    })

userprofile/templates/userprofile/edit_profile.html
{% extends 'core/layout.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'userprofile/css/edit_profile.css' %}"> 
{% endblock %}

{% block title %} Edit Profile | {% endblock %}

{% block body %}

<div class="edit-profile">
    {% if form.errors %}
        {% for fields in form %}
            {% for error in fields.errors %}
            <div class="alert-editprofile alert alert-danger">
                <strong> {{ error|escape }} </strong>
            </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert-editprofile alert alert-danger">
                <strong> {{ error|escape }} </strong>
            </div>
        {% endfor %}
    {% endif %}

    <div class="alert-editprofile alert alert-danger hidden" id="file-size-error">

        <strong>Image file exceeds {{max_file_size}} mb size limit </strong>
    </div>
    <div class="alert-editprofile alert alert-danger hidden" id="file-type-error">
        <strong> File must be type image </strong>
    </div>

    <div class="edit-profile-form info-card">
        <!-- default encoding type: (application/x-www-form-urlencoded => It URL-encodes the form data and appends it to the URL as query parameters when the form is submitted. This is suitable for sending simple text data but not suitable for uploading files or binary data.)
        custom encoding type: (multipart/form-data => This encoding type is used when you need to upload files. It splits the form data into multiple parts and encodes them individually, allowing for the safe transmission of binary data. The server can then reconstruct the data on the backend to handle file uploads correctly.)                    -->

        <form action="{% url 'userprofile:edit_profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="edit-profile-form-fields form-group">
                {{ form.name.label_tag }}
                {{ form.name }}
            </div>
            <div class="edit-profile-form-fields form-group">
                {{ form.date_of_birth.label_tag }}
                {{ form.date_of_birth }}
            </div>
            <div class="edit-profile-form-fields form-group">
                {{ form.about.label_tag}}
                {{ form.about}}
                <div id="character-counter"> 225 characters remaining </div>
            </div>
            <div class="edit-profile-form-fields form-group">
                {{ form.country.label_tag }}
                {{ form.country }}
            </div>
            <div class="edit-profile-form-fields form-group">
                {{ form.image.label_tag }}
                <div class="custom-image">
                    <!-- Accept="image/*": Types of files that the server accepts. -->
                    <input type="file" name="image" class="custom-image-input" accept="image/*" id="image_id">
                    <!-- <label class="custom-image-label" data-browse="Browse" for="image_id" data-default="Choose file"> Choose file </label> -->
                </div>
            </div>
            <button class="btn btn-light btn-sm" name="cancel" value="clicked"> Cancel </button>
            <input type="submit" class="btn btn-sm btn-info" value="save" id="id_edit_profile_save_btn">
        </form>
    </div>
   </div>

{% endblock %}

{% block script %}
    <script src="{% static 'userprofile/js/edit_profile.js' %}"></script>
{% endblock %}

userprofile/templates/userprofile/user_profile.html
{% extends 'core/layout.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'userprofile/css/styles.css' %}"> 
{% endblock %}

{% block title %} User Profile | {% endblock %}

{% block body %}

<div class="container mb-3">
    <div class="user-profile mb-3">
        {% if user_data.image.url %}
           <img id="id_user_profile_img" src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="round-picture profile-picture">
        {% endif %}
        
        {% if user.profile.name %}
            <h2 id="id_username"> {{user.profile.name}} </h2>
        {% else %}
            <h2 id="id_username"> {{user.username}} </h2>
        {% endif %}
        

        <div class="d-flex justify-content-space-around">
            {% if request.user.is_authenticated %}
            <a href="{% url 'userprofile:edit_profile' %}">
                <button class="mb-3 mt-3 m-2" id="id_edit_profile_btn">
                    <i class="fas fa-pencil-alt"></i> Edit Profile
                </button>
            </a>

            <a href="{% url 'core:change_password' %}">
                <button class="mb-3 mt-3 m-2" id="id_edit_profile_btn">
                    <i class="fas fa-key"></i> change password
                </button>
            </a>

            <a href="{% url 'core:logout' %}">
                <button class="mb-3 mt-3 m-2" id="id_edit_profile_btn">
                    <i class="fas fa-sign-out"></i> logout
                </button>
            </a>
            {% endif %}
        </div>
    </div>
    
    <div class="card bio info-card text-muted user-bio">
        <div class="profile-item">
            <label><i class="fas fa-user profile-icon"></i> Name </label>
            <p>
                {{ user.profile.name|default:"---" }}
            </p>
        </div>
        
        <div class="profile-item">
            <label><i class="fas fa-hourglass-start profile-icon"></i> Birth</label>
            <p>
                {{ user.profile.date_of_birth|date:"d.m.Y"|default:"---" }}
            </p>
        </div>

        <div class="profile-item">
            <label><i class="fas fa-globe profile-icon"></i> Country </label>
            <p>
                {{ user.profile.country.name|default:"---" }}
            </p>
        </div>

        <div class="about">
            <label><i class="fas fa-pencil-square profile-icon"></i> About </label>
            <p class="about-text text-muted">
                {{ user.profile.about|default:"---" }}
            </p>
        </div>
    </div>

</div>

{% endblock %}