core/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('change_password/', views.change_password, name='change_password'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'), name='password_reset_complete'),

    path('plans/', views.plans, name='plans'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('user_manual/', views.user_manual, name='user_manual'),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('project/', include('project.urls')),
    path('userprofile/', include('userprofile.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('post', views.post, name='post'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('detail_post/<int:post_id>/', views.detail_post, name='detail_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('upload_image_edit/<int:post_id>/', views.upload_image_edit, name='upload_image_edit'),
    
    # path('get_image_url/<int:image_id>/', views.get_image_url, name='get_image_url'),
    path('delete/', views.delete_images, name='deleteImages'),
    path('get-temporary-image-url/<int:image_id>/', views.get_temporary_image_url, name='get_temporary_image_url'),
    path('edit_post/<int:post_id>/get-temporary-image-url-edit/<int:image_id>/', views.get_temporary_image_url_edit, name='get_temporary_image_url_edit'),
    path('get-image/<str:signed_value>/', views.get_image, name='get_image'),
    path('edit_post/<int:post_id>/get-image/<str:signed_value>/', views.get_image_edit, name='get_image_edit'),
    path('detail_post/<int:post_id>/get-image/<str:signed_value>/', views.get_image_detail_post, name='get_image_detail_post'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.db import models
from core.models import User

from django.urls import reverse
from django.conf import settings
import os
from django.db.models.signals import post_delete
from django.dispatch import receiver
    
# Create your models here.
class Project(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='projects')
    title = models.CharField(max_length=225)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def num_posts_todo(self):
        return self.posts.filter(status=Post.TODO).count()


class Post(models.Model):
    TODO = 'todo'
    DONE = 'done'
    ARCHIVED = 'archived'

    CHOICES_STATUS = [
        (TODO, 'Todo'),
        (DONE, 'Done'),
        (ARCHIVED, 'Archived')
    ]

    project = models.OneToOneField(Project, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=225)
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=TODO)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Post {self.id}: {self.title}"
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": str(self.pk)})


def user_directory_path(instance, filename):
    base_name = os.path.basename(filename)
    name,ext = os.path.splitext(base_name)

    return "post/user/"+ str(instance.user.id)+"/"+name +ext #removing and adding spaces might cause some errors in the path structure...
    # return "post/user/"+ str(instance.post.project.user.id) + "/"+ str(instance.post.id)+ "/"+"IMG_" + str(instance.post.id)+"_"+name +ext

    
# class Images(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to=user_directory_path)

# @receiver(post_delete, sender=Images)
# def delete_image_file(sender, instance, **kwargs):
#     # Delete the file from the media folder when the record is deleted
#     if instance.image:
#         try:
#             if os.path.isfile(instance.image.path):
#                 os.remove(instance.image.path)
#         except Exception as e:
#             # Log any errors that occur during file deletion
#             print(f"Error deleting file: {str(e)}")

class Img(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_images')
    img = models.ImageField(upload_to=user_directory_path)

@receiver(post_delete, sender=Img)
def delete_image_file(sender, instance, **kwargs):
    # Delete the file from the media folder when the record is deleted
    if instance.img:
        try:
            if os.path.isfile(instance.img.path):
                os.remove(instance.img.path)
        except Exception as e:
            # Log any errors that occur during file deletion
            print(f"Error deleting file: {str(e)}")

project/forms.py
from django import forms
from .models import Post, Img

from django.core.exceptions import ValidationError
from django.conf import settings

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'style':'width:280px;','autofocus':'autofocus', 'autocomplete':'off', 'class':'form-control', 'id':'id_title', 'placeholder':'Doc title...'}),
            'content': forms.Textarea(attrs={'rows':18, 'cols':20, 'autocomplete':'off', 'class':'form-control', 'id':'id_content', 'placeholder':'start writing...'})
        }

# class PostFullForm(PostForm):
#     post_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
#     images = forms.FileField(widget=forms.ClearableFileInput(attrs={}),required=False)

#     def clean_images(self):
#         images = self.cleaned_data.get('images')
#         print('image type:',type(images))
                
#     class Meta(PostForm.Meta):
#         fields = PostForm.Meta.fields


class ImageUploadForm(forms.Form):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={}), required=False)

    def clean_images(self):
        images = self.cleaned_data.get('images')
        return images

project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from project.models import Project, Post, Img, user_directory_path
from django.contrib import messages
from .forms import PostForm, ImageUploadForm

from django.conf import settings
from django.core.exceptions import ValidationError

from django.http import JsonResponse, HttpResponse, HttpResponseRedirect, HttpResponseNotAllowed
from django.urls import reverse
from django.core.signing import Signer, BadSignature
from django.utils import timezone
from datetime import timedelta

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from markdown2 import Markdown


# Create your views here.
def projects(request):
    projects = Project.objects.filter(user=request.user).all()

    paginator = Paginator(projects, 8)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)

    return render(request, 'project/projects.html', {
        'projects': projects,
        "page_obj": page_obj
    })


def delete_project(request, project_id):
    project = Project.objects.get(pk=project_id)
    if request.method == "POST":
        project.delete()
        return redirect('project:projects')
    else:
        return redirect('project:projects')



def post(request):
    # total_images = Images.objects.filter(post__project__user=request.user)
    
    total_images = Img.objects.filter(user=request.user)

    if request.method == "POST":
        form = PostForm(request.POST or None)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get('title')
            content = form.cleaned_data['content']

            if title:
                project = Project.objects.create(user=user, title=title)
                project.save()

            post = Post.objects.create(project=project, title=title, content=content)
            post.save()

            messages.info(request, 'Post created successfully!')
            return redirect('project:projects')
        else:
            return render(request, "project/post.html", {"form":form, "user_images":total_images})
        
    return render(request, 'project/post.html', {
        'form': PostForm(),
        "user_images":total_images,
    })




def upload_image(request):
    total_images = Img.objects.filter(user=request.user)
    redirect_url = reverse('project:post')

    if request.method == "POST":
        redirect_url = request.GET.get('next', reverse('project:post'))
        form = ImageUploadForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            try:
                images = request.FILES.getlist('images')
                # Count the total number of images uploaded by the user
                total_images_count = Img.objects.filter(user=request.user).count()

                # Check if the user has exceeded the maximum limit (10 images)
                if total_images_count + len(request.FILES.getlist('images')) > 10:
                    raise ValidationError("You can upload a maximum of 10 images. Delete some previous images to add more.")
                
                images = request.FILES.getlist('images')
                # Check if the number of images exceeds 3
                if images and len(images) > 3:
                    raise ValidationError("You can upload a maximum of 3 images.")

                for image in images:
                    # Handle image uploads here
                    if image.size > settings.MAX_UPLOAD_SIZE * 1024 * 1024:
                        raise ValidationError(f"Image file {image.name} exceeds {settings.MAX_UPLOAD_SIZE} MB size limit")
                    img_instance = Img(user=request.user, img=image)  # Create Img instance
                    img_instance.save()  # Save the instance to the database

            except ValidationError as e:
                message = ''.join(e)
                return render(request, 'project/upload_image.html', {
                    "message": message,
                    "form": form,
                    "user_images": total_images,
                    "redirect": redirect_url
                })
            messages.info(request, 'Images uploaded successfully!')
            return redirect('project:upload_image')
    else:
        form = ImageUploadForm()
    return render(request, 'project/upload_image.html', {'form': form, "user_images": total_images, "redirect": redirect_url})


def detail_post(request, post_id):
    # Retrieve the post object using the post_id
    post = Post.objects.get(pk=post_id)
    total_images = Img.objects.filter(user=request.user)
    redirect_url = reverse("project:projects")
    return render(request, "project/detail_post.html", {
        "post":post,
        "post_content": markdown(post.content),
        "user_images": total_images,
        "redirect": redirect_url
    })


def edit_post(request, post_id):
    # Retrieve the post object using the post_id
    post = Post.objects.get(pk=post_id)
    total_images = Img.objects.filter(user=request.user)
    # If the request method is POST, validate the form and save changes
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.info(request, 'Post edited successfully!')
            return redirect('project:detail_post', post_id=post_id)
    # If the request method is GET, create a form populated with the post's current data
    else:
        form = PostForm(instance=post)
    # Render the form in a template
    return render(request, "project/edit_post.html", {"form":form, "post":post, "user_images": total_images})



def upload_image_edit(request, post_id):
    total_images = Img.objects.filter(user=request.user)
    redirect_url = reverse('project:edit_post', args=(post_id,))

    if request.method == "POST":
        redirect_url = request.GET.get('next', reverse('project:edit_post', args=(post_id,)))
        form = ImageUploadForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            try:
                images = request.FILES.getlist('images')
                # Count the total number of images uploaded by the user
                total_images_count = Img.objects.filter(user=request.user).count()

                # Check if the user has exceeded the maximum limit (10 images)
                if total_images_count + len(request.FILES.getlist('images')) > 10:
                    raise ValidationError("You can upload a maximum of 10 images. Delete some previous images to add more.")
                
                images = request.FILES.getlist('images')
                # Check if the number of images exceeds 3
                if images and len(images) > 3:
                    raise ValidationError("You can upload a maximum of 3 images.")

                for image in images:
                    # Handle image uploads here
                    if image.size > settings.MAX_UPLOAD_SIZE * 1024 * 1024:
                        raise ValidationError(f"Image file {image.name} exceeds {settings.MAX_UPLOAD_SIZE} MB size limit")
                    img_instance = Img(user=request.user, img=image)  # Create Img instance
                    img_instance.save()  # Save the instance to the database

            except ValidationError as e:
                message = ''.join(e)
                return render(request, 'project/upload_image_edit.html', {
                    "message": message,
                    "form": form,
                    "user_images": total_images,
                    "redirect": redirect_url,
                    "post_id":post_id
                })
            messages.info(request, 'Images uploaded successfully!')
            return HttpResponseRedirect(reverse('project:upload_image_edit', args=(post_id,)))
    else:
        form = ImageUploadForm()
    return render(request, 'project/upload_image_edit.html', {'form': form, "user_images": total_images, "redirect": redirect_url, "post_id":post_id})


def get_temporary_image_url(request, image_id):
    try:
        image = Img.objects.get(id=image_id)
        image_url = image.img.url
        signer = Signer()
        timestamp = int(timezone.now().timestamp())
        signed_value = signer.sign(f'{image_id}-{timestamp}')
        return JsonResponse({'image_url': f'get-image/{signed_value}/'})
    except Img.DoesNotExist:
        return JsonResponse({'error': 'Image not found'}, status=404)
    
def get_image(request, signed_value):
    signer = Signer()
    try:
        image_id, timestamp = signer.unsign(signed_value).split('-')
        image = Img.objects.get(id=image_id)
        return redirect(image.img.url)
    
        # Check if the request is made within a certain time window (e.g., 5 minutes)
        # if int(timezone.now().timestamp()) - int(timestamp) <= 300:  
        #     return redirect(image.image.url)
        # else:
        #     return HttpResponse('Link expired.', status=403)

    except (BadSignature, ValueError, Img.DoesNotExist):
        return HttpResponse('Invalid link.', status=403)
    
    
def get_temporary_image_url_edit(request, image_id, post_id):
    return get_temporary_image_url(request, image_id)

def get_image_edit(request, signed_value, post_id):
    return get_image(request, signed_value)

def get_image_detail_post(request, signed_value, post_id):
    return get_image(request, signed_value)

def delete_images(request):
    if request.method == "POST":
        selected_image_ids = request.POST.getlist('selected_image_ids')

        # Delete selected Img
        Img.objects.filter(id__in=selected_image_ids).delete()

    return redirect('project:upload_image')


def markdown(content):
    markdowner = Markdown()

project/templates/project/detail_post.html
{% extends 'core/layout.html' %}
{% load static %}
{% load filters %}

{% block title %} Detail Post {% endblock %}

{% block body %}

<div class="mt-3">
    <h3 class="text-center"> &laquo; Project: {{post.project.title|truncatechars:50}} &raquo; </h3>
    <hr>
    <div class="text-center m-2">
        <a id="id_editpost_btn" href="{% url 'project:edit_post' post.id %}"> Edit </a>
    </div>
    
    <div class="d-flex justify-content-center align-items-center mt-3">
        <div id="id_detail_content">
            <p>
                {{post_content|safe}}
            </p>
        </div>
    </div>

    <div class="text-center mt-3">
        {% if redirect %}
          <a style="text-decoration: none; color: gray;" href="{{redirect}}"> &laquo; go back &raquo; </a>
        {% endif %} 
      </div>
</div>

{% endblock %}

project/templates/project/paginator.html
<nav class="page-nav bg-light-subtle">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; first </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; Previous </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="?page=1">&laquo; first </a>
        </li>
        <!-- when you are already on the first page, and the code is trying to generate a "Previous" link that points to page 0, ERROR: raise EmptyPage(_('That page number is less than 1')) -->
        <li class="page-item disabled">
            <a class="page-link" href="?page=1"> &laquo; Previous </a>
        </li>
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}"> next &raquo; </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> last &raquo; </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> next &raquo; </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> last &raquo; </a>
        </li>
        {% endif %}
    </ul>
    <div class="current-page">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </div>
</nav>

project/templates/project/post.html
{% extends 'core/layout.html' %}
{% load static %}
{% load mathjax %}
{% load filters %}

{% block title %} Index {% endblock %}

{% block body %}
<div class="post-block row">
    <div class="sidebar col-lg-6 col-md-7 bg-light">

        <div>
            {% if message %}
            <p> {{message}} </p>
            {% endif %}
        </div>
        <div id="id_copy_image_url">
            <select name="uploads" id="uploads">
                <option disabled selected value="">select</option>
                {% for image in user_images %}
                <option value="{{image.id}}"> {{image.img.name|filename|truncatechars:25}} </option>
                {% endfor %}
            </select>
          
            <!-- <button id="id_copyBtn" onclick="copyToClipboard()">Copy URL</button> -->
            <button id="id_copyBtn" class="ml-2"> <i class="fas fa-copy"></i></button>
        </div>

        <!-- <h3> YOUR UPLOADS </h3>

        <form id="deleteForm" method="post" action="{% url 'project:deleteImages' %}">
          {% csrf_token %}
          <select name="uploads" id="uploads">
              <option disabled selected value="">select</option>
              {% for image in user_images %}
              <option value="{{image.id}}"> {{image.image.name|filename}} </option>
              {% endfor %}
          </select>

          <button onclick="copyToClipboard()">Copy URL</button> -->
        
          <!-- Add checkboxes for image selection -->
          <!-- <div id="imageSelection">
            {% for image in user_images %}
            <input type="checkbox" name="image_ids" value="{{ image.id }}">
            <label>{{ image.image.name|filename }}</label><br>
            {% endfor %}
          </div> -->
        
          <!-- Add button to delete selected images -->
          <!-- <button type="button" onclick="deleteImages()">Delete Selected</button>
        </form>         -->

        <form action="{% url 'project:post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- <div class="form-group">
                <label for="note-image">Images</label>
                <input type="file" name="images" class="form-control-file" id="note-image" multiple>
            </div> -->
            {% for fm in form %}
            {% if fm.name != 'post_id' and fm.name != 'images' %}
            <label> {{fm.label}}: </label>
            <div class="form-group">
                {{fm}}
            </div>
            {% endif %}
            {% endfor %}
            <div>
                <button id="id_save_post_btn" class="btn btn-sm btn-info"> save </button>
                <a href="{% url 'project:upload_image' %}" id="id_upload_image_url"> upload images </a>
            </div>
        </form>


    </div>
    <div class="main col-lg-6 col-md-7">
        <div id="display"></div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'project/js/post.js' %}"></script>


<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [['$', '$'], ['\\(', '\\)']],
            displayMath: [['$$', '$$'], ['\\[', '\\]']],
            processEscapes: true,
            processEnvironments: true,
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
            TeX: { equationNumbers: { autoNumber: "AMS" } }
        },
        showMathMenu: false
    });
</script>
<script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

<!-- marked -->
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked-footnote/dist/index.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/3.0.2/marked.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>

<script>

</script>

<!-- 
<script>
    function copyToClipboard() {
        var imageId = document.getElementById("uploads").value;
        if (!imageId) return;

        fetch(`get-temporary-image-url/${imageId}/`)
            .then(response => response.json())
            .then(data => {
                console.log(data.image_url)
                if (data.image_url) {
                    navigator.clipboard.writeText(data.image_url);
                    alert("Temporary Image URL copied to clipboard!");
                } else {
                    alert("Failed to fetch temporary image URL.");
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert("Failed to fetch temporary image URL.");
            });

      // Prevent the default form submission behavior
      event.preventDefault();
    }
    // Function to delete selected images
    function deleteImages() {
        var selectedImageIds = [];
        var checkboxes = document.querySelectorAll('input[name="image_ids"]:checked');
        checkboxes.forEach(function(checkbox) {
          selectedImageIds.push(checkbox.value);
        });

        if (selectedImageIds.length === 0) {
          alert("Please select images to delete.");
          return;
        }

        // Add selected image IDs to the form for submission
        var deleteForm = document.getElementById("deleteForm");
        selectedImageIds.forEach(function(imageId) {
          var input = document.createElement("input");
          input.setAttribute("type", "hidden");
          input.setAttribute("name", "selected_image_ids");
          input.setAttribute("value", imageId);
          deleteForm.appendChild(input);
        });

        // Submit the form
        deleteForm.submit();
      }
</script> -->


{% endblock %}

project/templates/project/projects.html
{% extends 'core/layout.html' %}
{% load static %}
{% load filters %}

{% block title %} Home {% endblock %}

{% block body %}
<div id="projects-app" class="">

    <!-- <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
    
            <li class="breadcrumb-item active"><a href="#" aria-current="page"> Projects </a></li>
        </ol>
    </nav> -->
    <div class="text-center m-3">
        <div class="">
            <a class="btn btn-outline-info m-3" href="{% url 'project:post' %}"> <i class="fas fa-plus"></i> Add Project </a>
            <hr>
            <!-- <button type="button" class="btn btn-success" onclick="$('#myModal').modal('toggle');">Add Project</button> -->
        </div>
    </div>

    <div class="projects d-flex justify-content-center align-items-center flex-wrap">
        {% for post in page_obj.object_list %}

        <div class="card mx-4 my-4 shadow-sm rounded" style="width: 20rem; height: 20rem;">
            <div class="card-body">
                <h3 id="id_post_card_title" class="card-title overflow-hidden"> {{post.title|truncatechars:16}} </h3>
                <hr>
                <p class="post-content card-text overflow-hidden"> {% if post.posts.content %} {{post.posts.content|truncatechars:45}} {% else %} <i class="fa-solid fa-eye-slash"></i> No content. {% endif %} </p>
                <p class="text-muted small"> last modified: {{post.posts.last_modified|timesince}} ago </p>
                <!-- <p> Tasks: {{post.num_tasks_todo }} </p> -->
                <p class="text-muted small"> posted {{post.posts.created_at|timesince}} ago </p>
                <hr>
                <div class="mt-auto d-flex justify-content-center">
                    <a href="{% url 'project:detail_post' post.id %}" class="btn btn-sm btn-secondary"> Details </a>


                    <!-- delete project button -->
                    {% if request.user == post.user %}
                    <div class="ml-3">
                        <button class="btn btn-sm btn-danger" onclick="$('#myModal').modal('toggle');" type="submit"> <i class="fas fa-trash-alt"></i> Delete </button>
                    </div>
                    {% endif %}
                </div>
            </div> 
        </div>

        <!-- delete project modal -->
        <div id="myModal" class="modal" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">

                    <form method="post" action="{% url 'project:delete_project' post.id %}">
                        {% csrf_token %}
        
                        <div class="modal-header">
                            <h5 class="modal-title"> Are you sure? </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    
                        <div class="modal-body">
                            Are you sure you want to permanently delete this project?
                        </div>
        
                        <footer class="modal-footer">
                            <button type="submit" class="btn btn-danger modal-save"> Delete </button>
                            <button type="button" class="btn btn-secondary modal-close" data-dismiss="modal"> Cancel </button>
                        </footer>
                    </form>
                </div>
            </div>
        </div>
        <!-- delete project modal -->


        {% empty %}
        <div class="card mx-3 my-3">
            <div class="card-body">
                no projects yet...
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block footer %}
<footer>
    <hr>
    {% include "project/paginator.html" %}
</footer>
{% endblock %}











        <!-- {% for project in projects %}
        <div class="card mx-3 my-3 shadow-sm rounded" style="width: 18rem;">
            <div class="card-body">
                <h3 class="card-title"> {{project.title}} </h3>
                <hr>
                <p class="post-content card-text overflow-hidden"> {{project.posts.content|truncatechars:45}} </p>
                <p class="text-muted small"> last modified: {{project.posts.last_modified|date:"M. d, Y H:i" }} </p> -->
                <!-- <p> Tasks: {{project.num_tasks_todo }} </p> -->
                <!-- <p class="text-muted small"> posted {{project.posts.created_at|timesince}} ago </p>
                <hr>
                <div class="mt-auto d-flex justify-content-center">
                    <a href="#" class="btn btn-sm btn-secondary"> Details </a>
                </div>
            </div> 
        </div>
        {% endfor %} -->