core/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('change_password/', views.change_password, name='change_password'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'), name='password_reset_complete'),

    path('plans/', views.plans, name='plans'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('user_manual/', views.user_manual, name='user_manual'),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('project/', include('project.urls')),
    path('userprofile/', include('userprofile.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('post', views.post, name='post'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('detail_post/<int:post_id>/', views.detail_post, name='detail_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('upload_image_edit/<int:post_id>/', views.upload_image_edit, name='upload_image_edit'),
    
    # path('get_image_url/<int:image_id>/', views.get_image_url, name='get_image_url'),
    path('delete/', views.delete_images, name='deleteImages'),
    path('get-temporary-image-url/<int:image_id>/', views.get_temporary_image_url, name='get_temporary_image_url'),
    path('edit_post/<int:post_id>/get-temporary-image-url-edit/<int:image_id>/', views.get_temporary_image_url_edit, name='get_temporary_image_url_edit'),
    path('get-image/<str:signed_value>/', views.get_image, name='get_image'),
    path('edit_post/<int:post_id>/get-image/<str:signed_value>/', views.get_image_edit, name='get_image_edit'),
    path('detail_post/<int:post_id>/get-image/<str:signed_value>/', views.get_image_detail_post, name='get_image_detail_post'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    path('<int:user_id>/', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from .models import User

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from userprofile.models import UserProfile


# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def plans(request):
    return render(request, 'core/plans.html')

def privacy(request):
    return render(request, 'core/privacy.html')

def terms(request):
    return render(request, 'core/terms.html')

def contact(request):
    return render(request, 'core/contact.html')

def user_manual(request):
    return render(request, 'core/user-manual.html')


def login_view(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:index')
        else:
            return render(request, "core/login.html", {
                "message": "Invalid email and/or password!"
            })
    return render(request, "core/login.html")
        

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:index'))

def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']

        password = request.POST['password']
        confirmation = request.POST['confirmation']

        if password != confirmation:
            return render(request, 'core/register.html', {
                "message": "Passwords must match!"
            })
        
        try:
            user = User.objects.create_user(email, email, password)
            user.save()
        except IntegrityError:
            return render(request, 'core/register.html', {
                "message": "User already exists!"
            })
        login(request, user)

        try:
            user_profile = UserProfile.objects.get(user=request.user)
        except UserProfile.DoesNotExist:
            user_profile = UserProfile(user=request.user)
            user_profile.save()

        return HttpResponseRedirect(reverse("core:index"))
    return render(request, 'core/register.html')

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password has been changed successfully!')
            return redirect('core:index')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'core/change_password.html', {
        "form": form
    })

core/templates/core/change_password.html
{% extends 'core/layout.html' %}
{% load static %}

{% block title %} change password {% endblock %}

{% block body %}
{% if request.user.is_authenticated %}
<div id="id_auth_form" class="">
    {% for fm in form %}
        {% if fm.errors %}
        <div class="text-danger">
            {% for error in fm.errors %}
                <p class="">{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
    {% endfor %}

    <form action="{% url 'core:change_password' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for fm in form %}
                <div class="mb-3">
                    <label class="form-label">{{ fm.label }}</label>
                    {% for f in fm %}
                        <div class="input-group">
                            {{ f }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>

        <button class="btn btn-light btn-sm"> <a style="text-decoration: none; color: darkgray;" href="{% url 'userprofile:user_profile' request.user.id %}"> Cancel </a> </button>
        <button type="submit" class="btn btn-sm btn-info"> change password </button>
    </form>
    
</div>
{% endif %}

{% endblock %}

core/templates/core/contact.html
{% extends 'core/layout.html' %}
{% load static %}


{% block title %} contact | {% endblock %}

{% block body %}

<section class="row jumbotron jumbotron-fluid">
    <div class="container d-flex">
        <div>
            <h1 class="display-4" style="color: white;"> Con<span style="color:gray;">tact us</span> </h1>
            <h4 style="color:gray;"> some more inform<span style="color:gray;">ation...</span> </h4>
        </div>
    </div>
</section>

{% endblock %}

core/templates/core/index.html
{% extends 'core/layout.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block body %}
<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#343a40" fill-opacity="1" d="M0,32L20,42.7C40,53,80,75,120,112C160,149,200,203,240,208C280,213,320,171,360,154.7C400,139,440,149,480,176C520,203,560,245,600,234.7C640,224,680,160,720,117.3C760,75,800,53,840,85.3C880,117,920,203,960,240C1000,277,1040,267,1080,266.7C1120,267,1160,277,1200,256C1240,235,1280,181,1320,154.7C1360,128,1400,128,1420,128L1440,128L1440,0L1420,0C1400,0,1360,0,1320,0C1280,0,1240,0,1200,0C1160,0,1120,0,1080,0C1040,0,1000,0,960,0C920,0,880,0,840,0C800,0,760,0,720,0C680,0,640,0,600,0C560,0,520,0,480,0C440,0,400,0,360,0C320,0,280,0,240,0C200,0,160,0,120,0C80,0,40,0,20,0L0,0Z"></path></svg> -->
<section class="row jumbotron jumbotron-fluid">
    <div class="container d-flex">
        <div id="id_hero_welcome">
            <h1 class="display-3" style="color: white;"> We<span style="color:gray">lcome t</span>o TGN </h1>
            <p class="lead" style="color: gray;">Note taking made sim<span style="color:gray">ple <i class="fa-regular fa-clipboard"></i></span> </p>
        </div>
        <!-- <div>
            <img src="{% static 'core/css/images/TGN3.gif' %}" class="img-fluid" width="300" alt="Image">
        </div> -->
    </div>
</section>


<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div id="id_frontpage_para" class="row">
                <div class="col-md-6 image">
                    <img src="{% static 'core/css/images/typewriter.gif' %}" class="img-fluid" width="900" alt="Image">
                    <!-- <video width="320" height="240" controls>
                        <source src="{% static 'core/css/images/typewriter.mp4' %}" type="video/mp4">
                      </video> -->
                </div>

                <div class="col-md-6 text">
                    <h2 class="h4">Simple Note Taking</h2>

                    <p>Take a deep breath, relax, and let your thoughts flow effortlessly onto the digital page. With our MD editor, note-taking becomes a joy</p>
                </div>
            </div>

            <div id="id_frontpage_para" class="row">
                <div class="col-md-6 text">
                    <h2 class="h4">Effortless Note Taking</h2>

                    <p>Experience the ease of capturing your thoughts and ideas with our simple note-taking feature.</p>
                </div>

                <div class="col-md-6 image">
                    <img src="{% static 'core/css/images/front1.gif' %}" class="img-fluid" width="1100" alt="Image">
                </div>

            </div>

            <div id="id_frontpage_para" class="row">
                <div class="col-md-6 image">
                    <img src="{% static 'core/css/images/front2.gif' %}" class="img-fluid" width="1100" alt="Image">
                </div>

                <div class="col-md-6 text">
                    <h2 class="h4">Upload, Link, Copy</h2>

                    <p>With our MD editor, uploading <span style="font-weight: bolder;">images</span> is a breeze. Simply upload the image you want to add, and it's instantly integrated into your document. <br> No fuss, no hassle—just seamless image uploads that enhance your content.</p>
                </div>
            </div>

            {% if not request.user.is_authenticated %}

            <div class="text-center mt-3 mb-3">
                <div class="">
                    <h4> let's get started </h4>

                    <a href="{% url 'core:login' %}" class="btn btn-info"> Get a free account </a>
                </div>
            </div>

            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

core/templates/core/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %} finalproject {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static 'project/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'userprofile/css/styles.css' %}">

        {% block extra_css %}
        {% endblock %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Marcellus&family=Permanent+Marker&family=Poppins:wght@300;400;500;600;700;800;900&family=Satisfy&display=swap" rel="stylesheet">
    </head>
    <body class="body">

        <div id="navbar-app">
            <nav class="navbar navbar-expand-lg">
                <a class="navbar-brand" href="{% url 'core:index' %}" id="id_tgn_logo">
                    TheGoodNote
                </a>

                <div class="ml-auto">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:index' %}"> Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:plans' %}"> plans </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:user_manual' %}"> manual </a>
                        </li>

                        {%if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url 'project:projects' %}" class="nav-link"> Projects </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link btn btn-sm btn-info" href="{% url 'userprofile:user_profile' user_id=request.user.id %}">
                                    {% if request.user.profile.image.url %}
                                        <img class="post-image" alt="{{request.user.username}}" src="{{request.user.profile.image.url}}" width="100">
                                    {% else %}
                                        <span class="icon"><i class="fas fa-user"></i></span>
                                    {% endif %}

                                    <span>
                                        {% if not request.user.profile.name %} 
                                            {% firstof request.user.get_full_name request.user.username %}
                                        {% else %} 
                                            {{request.user.profile.name}}
                                        {% endif %}
                                    </span>
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link btn btn-sm btn-info" href="{% url 'core:login' %}"> login </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>

        <!-- Main -->
        <section class="section">
            {% if messages %}
                {% for message in messages %}
                    <p style="font-size: medium;" class="alert alert-success alert-dismissable"> <i class="fas fa-check-circle"></i> {{message}} </p>
                {% endfor %}
            {% endif %}

            {% block body %}
            {% endblock %}
        </section>

        <!--footer -->
        <footer style="margin-top: 35%;">
            {% block footer %}
            {% endblock %}
            <div class="text-center bg-light">
            <!-- Grid container -->
            <div class="container p-4">
                <!--Grid row-->
                <div class="row">
                  <!--Grid column-->
                  <div class="col-lg-12 col-md-6 mb-4 mb-md-0">
                    <!-- <h5 class="text-uppercase">Links</h5> -->
                    <h5 class=""> Links </h5>
            
                    <ul class="list-unstyled mb-0">
                      <li>
                        <a href="{% url 'core:contact' %}" class="text-body"> contact </a>
                      </li>
                      <li>
                        <a href="{% url 'core:privacy' %}" class="text-body"> Privacy policy </a>
                      </li>
                      <li>
                        <a href="{% url 'core:terms' %}" class="text-body"> Terms & conditions </a>
                      </li>
                    </ul>
                  </div>
                  <!--Grid column-->
                </div>
                <!--Grid row-->
              </div>
              <!-- Grid container -->
            
              <!-- Copyright -->
              <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
                  copyright &copy; 2024
                <a class="text-body" href="">TGN</a>
              </div>
              <!-- Copyright -->
            </div>
          </footer>


        <!-- javascript -->
        <script src="https://kit.fontawesome.com/b930e26f61.js" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        
        {% block script %}
        {% endblock %}

        <!-- javascript -->
    </body>
</html>

core/templates/core/login.html
{% extends 'core/layout.html' %}
{% load static %}

{% block title %} login {% endblock %}

{% block body %}

<div id="id_auth_form" class="">
    <div class="text-danger">
        {% if message %}
        <p> {{message}} </p>
        {% endif %}
    </div>
    
    <div>
        <form action="{% url 'core:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" name="email" id="id_email" placeholder="Enter your email" class="form-control" autocomplete="new-password" required>
            </div>
            <div class="form-group">
                <input type="password" name="password" id="id_password" placeholder="Enter your password" class="form-control" autocomplete="new-password" required>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-sm btn-info" value="login">
                <a id="id_forgot_password" class="border border-dark-subtle border-1 rounded p-2 ml-3" href="{% url 'core:password_reset' %}"> forgot password? </a>
            </div>
        </form>
    
    Don't have an account? <a href="{% url 'core:register' %}"> register </a>
    </div>
</div>

{% endblock %}

core/templates/core/password_reset.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Password Reset {% endblock %}

{% block body %}

<div id="id_auth_form" class="">
    <h3> &raquo; Reset password &laquo; </h3>
    <hr>
    {% if fm.errors %}
    <div class="text-danger">
        {% for error in fm.errors %}
            <p class="alert alert-danger"> {{error}} </p>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for fm in form %}
            <div class="mb-3">
                <label> {{fm.label}} </label>
                {% for f in fm %}
                    <div class="input-group">
                        {{f}}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        </div>
        <button type="submit" class="btn btn-sm btn-info"> submit </button>
        <a id="id_forgot_password" class="border border-dark-subtle border-1 rounded p-2 ml-3" href="{% url 'core:login' %}"> &raquo; go back &laquo; </a>
    </form>
</div>

{% endblock %}

core/templates/core/password_reset_complete.html
{% extends 'core/layout.html' %}
{% load static %}
{% block body %}


<div>
    <h3> &raquo; Reset password &laquo; </h3>
    <hr>
    <p> Your password has been set. You may go ahead & <a href="{% url 'core:login' %}"> sing in </a> now. </p>
</div>

{% endblock %}

core/templates/core/password_reset_confirm.html
{% extends 'core/layout.html' %}
{% load static %}
{% block body %}

<div id="id_auth_form" class="">
    <h3> &raquo; Reset password &laquo; </h3>
    <hr>
    {% if validlink %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for fm in form %}
            <div class="mb-3">
                <label> {{fm.label}} </label>
                {% for f in fm %}
                    <div class="input-group">
                        {{f}}
                    </div>
                {% endfor %}
                {% if fm.errors %}
                    <div class="text-danger col-md-5 col-lg-4 mt-2">
                        {% for error in fm.errors %}
                            <p class="alert alert-danger mb-1 mt-1 col-md-5 col-lg-4"> {{error}} </p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        </div>
        <button type="submit" class="btn btn-sm btn-info"> change password </button>
    </form>
    {% else %}
    
    <p>Unfortunately, the password reset link you've used is invalid or has already been used. If you still need to reset your password:</p>
    <ul>
      <li> Please request for new password reset link. </li>
      <li> Ensure you're using the most recent password reset link sent to your email. </li>
      <li> If you requested multiple password resets, use the link from the latest email. </li>
    </ul>
    
    {% endif %}
</div>

{% endblock %}

core/templates/core/password_reset_done.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Password Reset {% endblock %}

{% block body %}

<div id="id_auth_form" class="">
  <h3> &raquo; Reset password &laquo; </h3>
  <hr>
  <p>We've sent you instructions to reset your password. If you haven't received the email:</p>

  <ul>
    <li>Double-check that you entered the correct email address.</li>
    <li>Check your spam or junk mail folder.</li>
    <li>Wait a few minutes and refresh your inbox.</li>
  </ul>
</div>

{% endblock %}

core/templates/core/plans.html
{% extends 'core/layout.html' %}
{% load static %}


{% block title %} Plans | {% endblock %}

{% block body %}

<section class="row jumbotron jumbotron-fluid">
    <div class="container d-flex">
        <div>
            <h1 class="display-4" style="color: white;"> plan<span style="color:gray;">s</span> </h1>
            <h4 style="color:gray;"> Find the most sui<span style="color:gray;">table plan</span> for you. </h4>
        </div>
    </div>
</section>

<div class="row mt-6 d-flex justify-content-center">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title"> Basic </h3>
                <hr>
                <p class="card-text"> $1.6 </p>
                <ul>
                    <li> Unlimited Projects  </li>
                    <li> Upto 10 images uploads </li>
                    <li> Charged on <span style="font-weight: bolder;">monthly</span> basis </li>
                </ul>

                <hr class="my-2">
                <div class="d-flex justify-content-center">
                    <a href="" class="btn btn-sm btn-info"> Get started </a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title"> Pro </h3>
                <hr>
                <p class="card-text"> $20 </p>
                <ul>
                    <li> Unlimited Projects  </li>
                    <li> Unlimited images </li>
                    <li style="font-weight: bolder;"> Lifetime Access </li>
                </ul>

                <hr class="my-2">
                <div class="d-flex justify-content-center">
                    <a href="" class="btn btn-sm btn-warning"> Get started </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/privacy.html
{% extends 'core/layout.html' %}
{% load static %}


{% block title %} Privacy policy | {% endblock %}

{% block body %}

<section class="row jumbotron jumbotron-fluid">
    <div class="container d-flex">
        <div>
            <h1 class="display-4" style="color: white;">Priva<span style="color:gray;">cy Policy</span> </h1>
            <h4 style="color:gray;"> some more inform<span style="color:gray;">ation...</span> </h4>
        </div>
    </div>
</section>

{% endblock %}

core/templates/core/register.html
{% extends 'core/layout.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block body %}

<div id="id_auth_form" class="">
    <div class="text-danger">
        {% if message %}
        <p> {{message}} </p>
        {% endif %}
    </div>
    
    <div>
        <form action="{% url 'core:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" id="id_registration_username" placeholder="Enter your username" class="form-control" autofocus autocomplete="new-password" required>
            </div>
            <div class="form-group">
                <input type="email" name="email" id="id_email" placeholder="Enter your email" class="form-control" autocomplete="new-password" required>
            </div>
            <div class="form-group">
                <input type="password" name="password" id="id_password" placeholder="Create password" minlength="8" class="form-control" autocomplete="new-password" pattern="(?=.*[a-zA-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}" title="Password must contain at least one letter, one number, and one special character, and be at least 8 characters long." required>
            </div>
            <div class="form-group">
                <input type="password" name="confirmation" id="id_confirmation" placeholder="Confirm your password" minlength="8" class="form-control" autocomplete="new-password" required>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-sm btn-info" value="register">
            </div>
        </form>
    Already have an account? <a href="{% url 'core:login' %}"> login </a>
    </div>
</div>

{% endblock %}

core/templates/core/terms.html
{% extends 'core/layout.html' %}
{% load static %}


{% block title %} Terms & condition | {% endblock %}

{% block body %}

<section class="row jumbotron jumbotron-fluid">
    <div class="container d-flex">
        <div>
            <h1 class="display-4" style="color: white;">Ter<span style="color:gray;">ms & cond</span>tion  </h1>
            <h4 style="color:gray;"> some more inform<span style="color:gray;">ation...</span> </h4>
        </div>
    </div>
</section>

{% endblock %}